version: "3.8"

services:
  app:
    image: node
    volumes:
      - ./:/app
    tty: true
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - "npm i -g pnpm && pnpm i && tail -f /dev/stdout"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/localstack.sock
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "localstack-vol:/var/lib/localstack"
      - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "/var/run/localstack.sock:/var/run/localstack.sock"

volumes:
  localstack-vol: